[book]
authors = ["Johannes Wünsche"]
language = "en"
multilingual = false
src = "src"
title = "Haura Developer Guide"

[output.html]
site-url = "/haura/"

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false

