name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  dependencies:
    name: Dependencies
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "${HOME}/.cargo/env"
          rustup toolchain install stable --profile minimal --force
          echo "RUSTC_VERSION=$(rustc --version | grep --only-matching '[0-9]\+\.[0-9]\+\.[0-9]\+' | head --lines=1)" >> $GITHUB_ENV
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        # Environment variables do not seem to work, use ~ instead.
        with:
          path: |
            ~/.cargo
            target
          key: ubuntu-22.04-rustc-${{ env.RUSTC_VERSION }}-${{ hashFiles('**/Cargo.toml') }}
      - name: Build dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        # We need to manually clean Haura until there is a way to build only dependencies.
        # https://github.com/rust-lang/cargo/issues/2644
        run: |
          cd betree/tests
          cargo build --tests
          cargo clean --package betree-tests
          cd ..
          cargo build --tests
          cargo clean --package betree_storage_stack
  betree-integration:
    name: Integration Tests
    needs: dependencies
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "${HOME}/.cargo/env"
          rustup toolchain install stable --profile minimal --force
          echo "RUSTC_VERSION=$(rustc --version | grep --only-matching '[0-9]\+\.[0-9]\+\.[0-9]\+' | head --lines=1)" >> $GITHUB_ENV
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        # Environment variables do not seem to work, use ~ instead.
        with:
          path: |
            ~/.cargo
            target
          key: ubuntu-22.04-rustc-${{ env.RUSTC_VERSION }}-${{ hashFiles('**/Cargo.toml') }}
      - name: Check dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          exit 1
      - name: Run integration tests
        env:
          HAURA_NUM_THREAD: 1
          QUICKCHECK_TESTS: 20
        run: |
          cd betree/tests
          ./scripts/ci-test.sh
  betree-unit:
    name: Unit Tests
    needs: dependencies
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "${HOME}/.cargo/env"
          rustup toolchain install stable --profile minimal --force
          echo "RUSTC_VERSION=$(rustc --version | grep --only-matching '[0-9]\+\.[0-9]\+\.[0-9]\+' | head --lines=1)" >> $GITHUB_ENV
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        # Environment variables do not seem to work, use ~ instead.
        with:
          path: |
            ~/.cargo
            target
          key: ubuntu-22.04-rustc-${{ env.RUSTC_VERSION }}-${{ hashFiles('**/Cargo.toml') }}
      - name: Check dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          exit 1
      - name: Run unit tests
        env:
          HAURA_NUM_THREAD: 8
          QUICKCHECK_TESTS: 20
        run: |
          cd betree
          ./tests/scripts/ci-test.sh
