name: ci-pr

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  betree:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Debug
      run: |
        echo $PWD
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    - name: Dependency Cache
      uses: Swatinem/rust-cache@ce325b60658c1b38465c06cc965b79baf32c1e72
    - name: Build
      run: |
        cd betree/tests
        cargo build
    - name: Run tests
      run: |
        cd betree/tests
        ./scripts/ci-test.sh

