name: ci-pr

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  betree-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs/ | sh -s -- -y
        source $HOME/.cargo/env
        rustup toolchain install --profile minimal --force stable
    - name: Build Cache
      uses: actions/cache@v3
      with:
        path: |
          $HOME/.cargo
          ./target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('betree/**/*.rs', 'bectl/**/*.rs', 'julea-sys/**/*.rs', 'julea-betree/**/*.rs') }} }}
    - name: Build
      run: |
        cd betree
        cargo build
  betree-integration:
    needs: [betree-build]
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build Cache
      uses: actions/cache@v3
      with:
        path: |
          $HOME/.cargo
          ./target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('betree/**/*.rs', 'bectl/**/*.rs', 'julea-sys/**/*.rs', 'julea-betree/**/*.rs') }} }}
    - name: Run integration tests
      env:
        HAURA_NUM_THREAD: 1
      run: |
        cd betree/tests
        ./scripts/ci-test.sh
    - name: Upload failure log
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: integration-failure.log
        path: betree/tests/fail.log
  betree-internal:
    needs: [betree-build]
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build Cache
      uses: actions/cache@v3
      with:
        path: |
          $HOME/.cargo
          ./target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('betree/**/*.rs', 'bectl/**/*.rs', 'julea-sys/**/*.rs', 'julea-betree/**/*.rs') }} }}
    - name: Run unit tests
      env:
        HAURA_NUM_THREAD: 8
      run: |
        cd betree
        ./tests/scripts/ci-test.sh
    - name: Upload failure log
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: unit-failure.log
        path: betree/fail.log
