name: pages-haura-getting-started

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Configure Pages
      uses: actions/configure-pages@v2
    - name: Dependency Cache
      uses: actions/cache@v3
      with:
        path: |
          $HOME/.cargo
        key: ${{ runner.os }}-cargo-mdbook
    - name: Install mdbook
      run: |
        apt update
        apt install cargo
        cargo install mdbook
    - name: Build book
      run: |
        cd docs
        $HOME/.cargo/bin/mdbook build
    - name: Upload Book Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./docs/book
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Deploy Pages
      id: deployment
      uses: actions/deploy-pages@v1
